### ISSUE TITLE
[BUG]: Selection helper text is sent to the ZK backend after clearing a project and sending a new prompt

### ISSUE THREAD

**Issue by greg-kcio** [KittyCAD/modeling-app#9004]
### Describe the bug

[Slack thread](https://kittycadworkspace.slack.com/archives/C06L2RHP9SL/p1763673734812959)

[Trace](https://ui.honeycomb.io/kittycad/environments/dev/datasets/text-to-cad/result/Fmtn9ut2d55/trace/m2LLLVcPDyd?fields[]=s_name&fields[]=s_serviceName&span=cb4dfe2fdc64ee17)

Jenna successfully prompted to create a cooling plate, then she manually deleted the KCL code, then prompted ZK "make a zip tie", and ZDS sent an empty user selection (File main.kcl, line 1, column 0 through line 1, column 0) with irrelevant helper text:

> The users main selection is the wall of a general-sweep (that is an extrusion, revolve, sweep or loft).
The source range though is for the original segment before it was extruded, you can add a tag to that segment in order to refer to this wall, for example "startSketchOn(someSweepVariable, face = segmentTag)"
But it's also worth bearing in mind that the user may have intended to select the sweep itself, not this individual wall, see later source ranges for more context. about the sweep

### Steps to Reproduce

1. Prompt to create something
2. Delete the KCL code
3. Prompt to create something else

### Expected Behavior

The client message should not contain any selection helper text when the KCL file is empty.

### Desktop OS

MacOS

### Version

staging 41cc1c5

**Comment by greg-motif** [comment]
cc @Irev-Dev because I remember you worked on the selection helper text.

**Comment by pierremtb** [comment]
Believe this was fixed in #8978, let's confirm

**Comment by greg-motif** [comment]
Not fixed on 3e2a4638.

https://github.com/user-attachments/assets/75031b15-c4da-440d-bce7-761edac9ed51

**Comment by pierremtb** [comment]
@greg-kcio @lf94 yeah we got the selection in both the modelingMachine (see bottom right status bar) and ZK input. This might be a selections bug? Larger than TTC? I think it might be this bug: https://github.com/KittyCAD/modeling-app/issues/8231

<img width="412" height="124" alt="Image" src="https://github.com/user-attachments/assets/a1aabe64-dbb5-4dcc-8a0c-ad8680e4ca51" />

**Comment by lee-at-zoo-corp** [comment]
It's possible. I had to force unset those selections to make it disappear from the ZK UI.
